#ifndef TETRISH_BRAIN_INPUT_H
#define TETRISH_BRAIN_INPUT_H

#include <stdbool.h>

typedef enum PlayerInputKey {
    PLAYER_INPUT_KEY_MOVE_LEFT,
    PLAYER_INPUT_KEY_MOVE_RIGHT,
    PLAYER_INPUT_KEY_LOCK_DOWN,
    PLAYER_INPUT_KEY_SOFT_DROP,
    PLAYER_INPUT_KEY_ROTATE_LEFT,
    PLAYER_INPUT_KEY_ROTATE_RIGHT,
    PLAYER_INPUT_KEY_HOLD,
    PLAYER_INPUT_KEY_COUNT,
} PlayerInputKey;

#endif