#ifndef TETRISH_BRAIN_STATIC_H
#define TETRISH_BRAIN_STATIC_H

#include <stdbool.h>

typedef enum TetrominoType {
    TETROMINO_TYPE_I,
    TETROMINO_TYPE_J,
    TETROMINO_TYPE_L,
    TETROMINO_TYPE_O,
    TETROMINO_TYPE_S,
    TETROMINO_TYPE_T,
    TETROMINO_TYPE_Z,
    TETROMINO_TYPE_COUNT,
} TetrominoType;

typedef enum TetrominoCellType {
    TETROMINO_CELL_I,
    TETROMINO_CELL_J,
    TETROMINO_CELL_L,
    TETROMINO_CELL_O,
    TETROMINO_CELL_S,
    TETROMINO_CELL_T,
    TETROMINO_CELL_Z,
    TETROMINO_CELL_EMPTY,
    TETROMINO_CELL_GARBAGE,
    TETROMINO_CELL_COUNT,
} TetrominoCellType;

typedef enum TetrominoDirection {
    TETROMINO_DIRECTION_0,
    TETROMINO_DIRECTION_R,
    TETROMINO_DIRECTION_2,
    TETROMINO_DIRECTION_L,
    TETROMINO_DIRECTION_COUNT,
} TetrominoDirection;

extern const TetrominoDirection TETROMINO_RIGHT_DIRECTION[TETROMINO_DIRECTION_COUNT];

extern const TetrominoDirection TETROMINO_LEFT_DIRECTION[TETROMINO_DIRECTION_COUNT];

extern const int TETROMINO_OFFSET[TETROMINO_TYPE_COUNT][TETROMINO_DIRECTION_COUNT][5][2];

#define TETROMINO_I_BOX_SIZE 5
#define TETROMINO_JLOSTZ_BOX_SIZE 3

extern const int TETROMINO_BOX_SIZE[TETROMINO_TYPE_COUNT] ;

extern const void* const TETROMINO_CELL[TETROMINO_TYPE_COUNT];
extern const int TETROMINO_STARTING_ROW[TETROMINO_TYPE_COUNT];
extern const int TETROMINO_STARTING_COL[TETROMINO_TYPE_COUNT];
extern bool (* const IS_TETROMINO_CELL_OCCUPIED[TETROMINO_TYPE_COUNT])(TetrominoType type, TetrominoDirection direction, int row, int col);

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 40
extern const int VISIBLE_ROW_IDX;

#endif